#!/usr/bin/env bash

# File based on mathiasbynens and kentcdodds .macos files!
# mathiasbynens — https://github.com/mathiasbynens/dotfiles/blob/master/.macos
# kentcdodds — https://github.com/kentcdodds/dotfiles/blob/master/.macos

# Run without downloading:
# curl https://raw.githubusercontent.com/teziovsky/dotfiles/main/.install_macos/.2_developer | bash
# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.1_dotfiles` has finished
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

###############################################################################
# Tezivosky's Customizations                                                  #
###############################################################################

echo -e "\n\n"
echo "##################################################"
echo -e "\nHello $(whoami)! Let's set up your developer directory! 🔥\n"
echo "##################################################"

# Create developer path
echo -e "\n"
echo "Creating developer path..."
echo "------------------------------------------------"

if [ ! -d "$HOME/Developer" ]; then
  mkdir "$HOME/Developer"
  echo "Developer path at $HOME/Developer - created 🔥"
else
  echo "Developer path at $HOME/Developer - already exists 👌"
fi

# Clone wsb repos
echo -e "\n"
echo "Cloning wsb repos..."
echo "------------------------------------------------"

wsbRepos=(
  "cup-tournament"
)
for wsbRepo in "${wsbRepos[@]}"; do
  if [ ! -d "$HOME/Developer/wsb/$wsbRepo" ]; then
    git clone -q git@github.com:teziovsky/$wsbRepo.git "$HOME/Developer/wsb/$wsbRepo"
    echo "$wsbRepo repo - cloned 🔥"
  else
    echo "$wsbRepo repo - already exists 👌"
  fi
done

# Clone cli repos
echo -e "\n"
echo "Cloning cli repos..."
echo "------------------------------------------------"

cliRepos=(
  "md-generate"
)
for cliRepo in "${cliRepos[@]}"; do
  if [ ! -d "$HOME/Developer/cli/$cliRepo" ]; then
    git clone -q git@github.com:teziovsky/$cliRepo.git "$HOME/Developer/cli/$cliRepo"
    echo "$cliRepo repo - cloned 🔥"
  else
    echo "$cliRepo repo - already exists 👌"
  fi
done

# Clone contributions repos
echo -e "\n"
echo "Cloning contributions repos..."
echo "------------------------------------------------"

contributionsRepos=(
  "vuelidate-vuelidate"
  "awesome-uses"
  "fig-autocomplete"
  "snippet-explorer"
)
for contributionsRepo in "${contributionsRepos[@]}"; do
  if [ ! -d "$HOME/Developer/contributions/$contributionsRepo" ]; then
    git clone -q git@github.com:teziovsky/$contributionsRepo.git "$HOME/Developer/contributions/$contributionsRepo"
    echo "$contributionsRepo repo - cloned 🔥"
  else
    echo "$contributionsRepo repo - already exists 👌"
  fi
done

# Clone raycast contributions repos
echo -e "\n"
echo "Cloning raycast contributions repos..."
echo "------------------------------------------------"

raycastContributionsRepos=(
  "extensions"
  "raycast-teziovsky-airtable"
  "raycast-multi-translate"
)
for raycastContributionsRepo in "${raycastContributionsRepos[@]}"; do
  if [ ! -d "$HOME/Developer/contributions/raycast/$raycastContributionsRepo" ]; then
    git clone -q git@github.com:teziovsky/$raycastContributionsRepo.git "$HOME/Developer/contributions/raycast/$raycastContributionsRepo"
    echo "$raycastContributionsRepo repo - cloned 🔥"
  else
    echo "$raycastContributionsRepo repo - already exists 👌"
  fi
done

# Clone recruitments - makadu repos
echo -e "\n"
echo "Cloning recruitments - makadu repos..."
echo "------------------------------------------------"

recruitmentsMakaduRepos=(
  "makadu-miedzy-lasem-a-cisza"
)
for recruitmentsMakaduRepo in "${recruitmentsMakaduRepos[@]}"; do
  if [ ! -d "$HOME/Developer/recruitments/makadu/$recruitmentsMakaduRepo" ]; then
    git clone -q git@github.com:teziovsky/$recruitmentsMakaduRepo.git "$HOME/Developer/recruitments/makadu/$recruitmentsMakaduRepo"
    echo "$recruitmentsMakaduRepo repo - cloned 🔥"
  else
    echo "$recruitmentsMakaduRepo repo - already exists 👌"
  fi
done

# Clone recruitments - idcom repos
echo -e "\n"
echo "Cloning recruitments - idcom repos..."
echo "------------------------------------------------"

recruitmentsIdcomRepos=(
  "idcom-vue-test"
  "idcom-tiles"
)
for recruitmentsIdcomRepo in "${recruitmentsIdcomRepos[@]}"; do
  if [ ! -d "$HOME/Developer/recruitments/idcom/$recruitmentsIdcomRepo" ]; then
    git clone -q git@github.com:teziovsky/$recruitmentsIdcomRepo.git "$HOME/Developer/recruitments/idcom/$recruitmentsIdcomRepo"
    echo "$recruitmentsIdcomRepo repo - cloned 🔥"
  else
    echo "$recruitmentsIdcomRepo repo - already exists 👌"
  fi
done

# Clone sites repos
echo -e "\n"
echo "Cloning sites repos..."
echo "------------------------------------------------"

sitesRepos=(
  "jakubsoboczynski"
  "jakubsoboczynski-next-v1"
  "rock-paper-scissors"
  "images-gallery"
  "vehicle-service-book"
  "movie-search-engine"
  "car-service-book-api"
  "lenovo-product-card"
  "car-service-book-v1"
  "qr-code-component"
)
for sitesRepo in "${sitesRepos[@]}"; do
  if [ ! -d "$HOME/Developer/sites/$sitesRepo" ]; then
    git clone -q git@github.com:teziovsky/$sitesRepo.git "$HOME/Developer/sites/$sitesRepo"
    echo "$sitesRepo repo - cloned 🔥"
  else
    echo "$sitesRepo repo - already exists 👌"
  fi
done

# Clone sites - petnal repos
echo -e "\n"
echo "Cloning sites - petnal repos..."
echo "------------------------------------------------"

petnalSitesRepos=(
  "petnal-web"
  "petnal-native"
)
for petnalSitesRepo in "${petnalSitesRepos[@]}"; do
  if [ ! -d "$HOME/Developer/sites/petnal/$petnalSitesRepo" ]; then
    git clone -q git@github.com:teziovsky/$petnalSitesRepo.git "$HOME/Developer/sites/petnal/$petnalSitesRepo"
    echo "$petnalSitesRepo repo - cloned 🔥"
  else
    echo "$petnalSitesRepo repo - already exists 👌"
  fi
done

# Clone linux macos repos
echo -e "\n"
echo "Cloning linux macos repos..."
echo "------------------------------------------------"

linuxMacosRepos=(
  "vps-setup-scripts"
)
for linuxMacosRepo in "${linuxMacosRepos[@]}"; do
  if [ ! -d "$HOME/Developer/linux_macos/$linuxMacosRepo" ]; then
    git clone -q git@github.com:teziovsky/$linuxMacosRepo.git "$HOME/Developer/linux_macos/$linuxMacosRepo"
    echo "$linuxMacosRepo repo - cloned 🔥"
  else
    echo "$linuxMacosRepo repo - already exists 👌"
  fi
done

# Clone courses repos
echo -e "\n"
echo "Cloning courses repos..."
echo "------------------------------------------------"

coursesRepos=(
  "js-na-frontach-zadania"
  "js-na-frontach-w05e02-continous-deployment"
)
for coursesRepo in "${coursesRepos[@]}"; do
  if [ ! -d "$HOME/Developer/courses/$coursesRepo" ]; then
    git clone -q git@github.com:teziovsky/$coursesRepo.git "$HOME/Developer/courses/$coursesRepo"
    echo "$coursesRepo repo - cloned 🔥"
  else
    echo "$coursesRepo repo - already exists 👌"
  fi
done
